export const courseSlugs = [
  "net-training",
  "agile-training",
  "spotfire-training",
  "fortinet-training",
  "git-training",
  "oracle-financials-india-localization-training",
  "servicenow-training",
  "oracle-fusion-cloud-technical-training",
  "hadoop-training",
  "hadoop-administration-training",
  "hadoop-testing-training",
  "oracle-fusion-financials-training",
  "oracle-fusion-hcm-training",
  "oracle-fusion-scm-training",
  "oracle-goldengate-training",
  "grunt-training",
  "gradle-training",
  "oracle-exadata-training",
  "selenium-training",
  "service-desk-manager-training",
  "oracle-hrms-training",
  "j2ee-training",
  "oracle-endeca-commerce-training",
  "seo-training",
  "oracle-iexpense-training",
  "service-desk-analyst-training",
  "scrum-training",
  "oracle-performance-tuning-training",
  "embedded-hardware-design-development-training",
  "hbase-training",
  "oracle-pl-sql-training",
  "java-spring-training",
  "oracle-ebs-training",
  "comptia-training",
  "confluence-training",
  "servicenow-admin-training",
  "ibm-netezza-training",
  "servicenow-scripting-training",
  "sharepoint-training",
  "oracle-hyperion-training",
  "commvault-training",
  "oracle-demantra-training",
  "ibm-cognos-tm1-training",
  "node-js-training",
  "cognos-administration-training",
  "cobit-training",
  "cloud-foundry-training",
  "oracle-hyperion-drm-training",
  "ibm-aix-training",
  "netsuite-training",
  "biztalk-server-training",
  "confluence-administration-training",
  "java-web-dynpro-training",
  "core-java-training",
  "nexus-training",
  "javafx-training",
  "biztalk-server-administrator-training",
  "javascript-training",
  "obia-training",
  "hyperion-fdqm-training",
  "jboss-training",
  "cognos-training",
  "hyperion-financial-management-training",
  "cyberark-training",
  "hyperion-planning-training",
  "tibco-activematrix-bpm-administration-training",
  "obiee-training",
  "jbpm-training",
  "citrix-netscaler-training",
  "cyberoam-administration-training",
  "tibco-amx-lifecycle-governance-training",
  "iphone-development-training",
  "obiee-administration-training",
  "cisco-ucs-administration-training",
  "cisco-ucs-training",
  "chef-devops-training",
  "cyberoam-certified-network-security-expert-training",
  "cyberoam-training",
  "openstack-training",
  "oracle-financials-training",
  "aws-training",
  "data-modeling-training",
  "idq-training",
  "checkpoint-training",
  "opentext-training",
  "data-scientist-course-training",
  "bamboo-administrator-training",
  "ansible-training",
  "oracle-adf-training",
  "data-visualization-and-dashboarding-fundamentals-training",
  "ethical-hacking-training",
  "bigdata-greenplum-dba-training",
  "anthillpro-training",
  "datastage-training",
  "oracle-apex-training",
  "apache-ambari-training",
  "asp-net-training",
  "tibco-activematrix-policy-director-training",
  "apache-flume-training",
  "tibco-be-training",
  "datastage-administrator-training",
  "oracle-oaf-training",
  "dell-boomi-training",
  "oracle-atg-training",
  "iot-training",
  "dell-boomi-integration-administrator-training",
  "oracle-procure-to-pay-training",
  "siebel-analytics-functional-training",
  "devops-training",
  "tibco-businessworks-6x-training",
  "siebel-business-analyst-training",
  "oracle-aia-training",
  "siebel-crm-training",
  "atg-system-administrator-training",
  "dimensional-data-modeling-training",
  "docker-training",
  "documentum-training",
  "tibco-bw-training",
  "oracle-apps-dba-training",
  "blue-coat-training",
  "adobe-cq5-system-administrator-training",
  "sitecore-training",
  "oracle-project-accounting-training",
  "solarwinds-training",
  "oracle-scm-training",
  "oracle-soa-training",
  "splunk-training",
  "soa-admin-training",
  "splunk-administration-training",
  "oracle-tm-training",
  "spss-training",
  "oracle-tuxedo-training",
  "tfs-training",
  "oracle-webcenter-training",
  "oracle-workflow-training",
  "oracle-service-bus-training",
  "palo-alto-training",
  "pega-training",
  "pentaho-training",
  "peoplesoft-admin-training",
  "peoplesoft-core-hrms-training",
  "peoplesoft-crm-training",
  "peoplesoft-data-management-training",
  "peoplesoft-financials-training",
  "peoplesoft-fscm-training",
  "peoplesoft-hrms-training",
  "peoplesoft-hrms-functional-training",
  "performance-testing-training",
  "perl-scripting-training",
  "pmp-training",
  "power-bi-training",
  "oracle-rac-training",
  "tibco-collabarative-information-manager-training",
  "ccnp-training",
  "ccna-training",
  "cassandra-administration-training",
  "ca-siteminder-training",
  "business-analytics-with-r-training",
  "build-and-release-engineer-training",
  "istqb-training",
  "itil-training",
  "oracle-primavera-training",
  "apache-cassandra-training",
  "prince2-training",
  "embedded-systems-product-design-life-cycle-training",
  "puppet-training",
  "python-training",
  "apache-kafka-training",
  "wso2-esb-training",
  "drools-training",
  "jenkins-training",
  "bootstrap-training",
  "elasticsearch-training",
  "oracle-apps-functional-training",
  "ibm-datapower-training",
  "ibm-cast-iron-training",
  "ibm-bpm-training",
  "scala-training",
  "apache-solr-training",
  "ibm-websphere-mq-training",
  "siebel-crm-admin-training",
  "apache-mahout-training",
  "jira-training",
  "fortiweb-training",
  "apache-spark-training",
  "apache-storm-training",
  "fuse-esb-training",
  "jira-administration-training",
  "jmeter-training",
  "ibm-mdm-training",
  "oracle-apps-technical-training",
  "emc-san-storage-training",
  "netezza-dba-training",
  "jquery-training",
  "informatica-mdm-training",
  "ibm-websphere-administration-training",
  "oracle-b2b-training",
  "ibm-tivoli-training",
  "ibm-unica-campaign-training",
  "ibm-watson-analytics-training",
  "informatica-training",
  "oracle-bi-publisher-11g-training",
  "websphere-esb-training",
  "julia-training",
  "ibm-websphere-commerce-server-training",
  "ibm-rational-build-forge-training",
  "juniper-training",
  "etl-testing-training",
  "embedded-kernel-rtos-development-training",
  "labview-training",
  "linux-training",
  "ibm-security-qradar-siem-training",
  "embedded-firmware-development-training",
  "ibm-message-broker-training",
  "manual-testing-training",
  "informatica-analyst-training",
  "informatica-ilm-training",
  "bluecat-training",
  "arcsight-training",
  "atlassian-bamboo-training",
  "oracle-bpm-training",
  "forescout-administrator-training",
  "tibco-iprocess-training",
  "sccm-training",
  "bluecat-security-and-advanced-configuration-training",
  "bluecat-ipam-essentials-training",
  "tibco-spotfire-administration-training",
  "bluecat-fundamental-training",
  "ibm-informix-training",
  "wpf-training",
  "fortianalyzer-training",
  "workday-training",
  "fortiauthenticator-training",
  "wordpress-training",
  "websphere-ilog-jrules-training",
  "winrunner-training",
  "fortigate-i-training",
  "ibm-bpm-admin-training",
  "windows-networking-training",
  "fortigate-ii-training",
  "websphere-transformation-extender-training",
  "websphere-process-server-training",
  "fortigate-iii-training",
  "oracle-crm-training",
  "sonicwall-training",
  "websphere-portal-developer-training",
  "websense-training",
  "webmethods-training",
  "appium-training",
  "weblogic-server-adminisration-training",
  "vmware-vsphere-training",
  "vmware-vcloud-director-training",
  "apttus-training",
  "juniper-networks-certified-internet-associate-training",
  "juniper-networks-certified-internet-professional-training",
  "juniper-networks-certified-internet-specialist-training",
  "oracle-dac-training",
  "mapreduce-training",
  "application-packaging-and-virtualization-training",
  "maven-training",
  "maximo-training",
  "oracle-data-guard-training",
  "mean-stack-training",
  "microsoft-azure-training",
  "microsoft-dynamics-ax-training",
  "odi-training",
  "oracle-dba-training",
  "sql-server-dba-training",
  "microstrategy-training",
  "microstrategy-administration-training",
  "mobile-application-testing-training",
  "mongodb-training",
  "ms-project-training",
  "triton-ap-data-administrator-training",
  "ptc-windchill-training",
  "msbi-training",
  "fortimail-training",
  "msbuild-training",
  "mulesoft-training",
  "neo4j-training",
  "netapp-training",
  "qa-training",
  "ssas-training",
  "qlik-sense-training",
  "qlikview-training",
  "microsoft-dynamics-crm-training",
  "rsa-archer-training",
  "vmware-training",
  "ssis-training",
  "ruby-cucumber-training",
  "business-analyst-training",
  "ssrs-training",
  "streamserve-training",
  "struts-training",
  "sun-solaris-administration-training",
  "vmware-nsx-training",
  "ruby-on-rails-training",
  "tableau-advanced-training",
  "vb-net-training",
  "vagrant-training",
  "urbancode-udeploy-training",
  "api-testing-training",
  "apigee-training",
  "appian-training",
  "salesforce-training",
  "saltstack-training",
  "palo-alto-essentials-ii-training",
  "palo-alto-networks-essentials-i-training",
  "unix-shell-scripting-training",
  "palo-alto-panorama-manage-multiple-firewalls-training",
  "ui-developer-training",
  "triton-ap-email-administrator-training",
  "android-training",
  "triton-ap-web-training",
  "alteryx-training",
  "agile-plm-training",
  "cloveretl-training",
  "tibco-activematrix-bpm-training",
  "tibco-activespaces-training",
  "tibco-activematrix-soa-training",
  "sql-server-training",
  "tableau-training",
  "tableau-server-training",
  "talend-training",
  "tensorflow-training",
  "teradata-training",
  "teradata-administration-training",
  "teamcity-training",
  "cyber-security-training",
  "testcomplete-training",
  "adobe-experience-manager-training",
  "sonicwall-advanced-administration-cssp-training",
  "sonicwall-network-security-basic-administration-cssa-training",
  "hp-arcsight-esm-security-administrator-training",
  "cryptography-training",
  "bitcoin-training",
  "forgerock-training",
  "react-js-training",
  "ibm-api-connect-training",
  "looker-training",
  "blockchain-training",
  "rpa-training",
  "rpa-business-analyst-training",
  "rpa-developer-advanced-training",
  "rpa-developer-basic-training",
  "rpa-infrastructure-training",
  "automation-anywhere-training",
  "blue-prism-training",
  "uipath-training",
  "kofax-training",
  "kofax-capture-training",
  "workfusion-training",
  "kryon-systems-training",
  "softomotive-training",
  "kapow-training",
  "thoughtonomy-training",
  "aws-architect-training",
  "machine-learning-training",
  "catia-training",
  "microsoft-dynamics-365-training",
  "aws-sysops-training",
  "coded-ui-training",
  "aws-technical-training",
  "aws-developer-training",
  "aws-database-training",
  "aws-lambda-training",
  "aws-devops-training",
  "continuous-integration-training",
  "nuget-training",
  "octopus-deploy-training",
  "github-training",
  "gitlab-training",
  "gerrit-training",
  "bitbucket-training",
  "comptia-security-plus-training",
  "azure-solutions-architect-training",
  "salesforce-developer-training",
  "adobe-analytics-training",
  "adobe-marketing-cloud-training",
  "adobe-creative-cloud-training",
  "puppet-fundamentals-training",
  "ibm-bluemix-training",
  "salesforce-app-builder-training",
  "salesforce-admin-training",
  "artificial-intelligence-course-training",
  "openspan-training",
  "iis-training",
  "iota-training",
  "liferay-training",
  "salesforce-service-cloud-training",
  "kubernetes-training",
  "openstack-administration-training",
  "informatica-pim-training",
  "informatica-multi-domain-mdm-training",
  "informatica-srm-training",
  "oracle-taleo-training",
  "informatica-big-data-edition-training",
  "ibm-integration-bus-training",
  "ibm-filenet-training",
  "salesforce-lightning-training",
  "ai-deep-learning-with-tensorflow-training",
  "impala-training",
  "elk-stack-training",
  "docker-kubernetes-training",
  "kibana-training",
  "kibana-data-analysis-training",
  "ranorex-training",
  "splunk-operational-intelligence-training",
  "vmware-training-bangalore",
  "aws-training-new-york",
  "tableau-training-new-york",
  "cyber-security-training-bangalore",
  "informatica-training-chennai",
  "cognos-training-new-york",
  "python-training-new-york",
  "selenium-training-new-york",
  "salesforce-training-chennai",
  "devops-training-chennai",
  "microsoft-azure-training-new-york",
  "hadoop-training-new-york",
  "qlikview-training-new-york",
  "salesforce-advanced-developer-training",
  "splunk-developer-training",
  "salesforce-admin-201-certification-training",
  "salesforce-appexchange-training",
  "apache-nifi-training",
  "salesforce-iot-training",
  "reactjs-with-redux-training",
  "adobe-analysis-workspace-training",
  "adobe-target-training",
  "adobe-audience-manager-training",
  "continuous-delivery-training",
  "ibm-cognos-cube-training",
  "ibm-cognos-integration-server-training",
  "openshift-administration-training",
  "openshift-training",
  "apache-zeppelin-training",
  "hadoop-hive-training",
  "datameer-training",
  "ibm-cognos-framework-manager-training",
  "ibm-cognos-planning-training",
  "liferay-application-developer-training",
  "liferay-platform-developer-training",
  "liferay-front-end-developer-training",
  "liferay-system-administrator-training",
  "liferay-fundamentals-training",
  "liferay-content-management-training",
  "python-django-training",
  "workday-hcm-techno-functional-training",
  "informatica-big-data-integration-training",
  "salesforce-training-dallas",
  "aws-data-warehouse-training",
  "splunk-training-dallas",
  "big-data-on-aws-training",
  "informatica-training-bangalore",
  "cognos-training-dallas",
  "python-training-dallas",
  "hadoop-training-dallas",
  "cyber-security-training-dallas",
  "qlikview-training-dallas",
  "iot-training-texas",
  "microsoft-azure-training-dallas",
  "selenium-training-dallas",
  "jboss-administration-training",
  "salesforce-einstein-analytics-training",
  "apache-camel-training",
  "ibm-linuxone-training",
  "adobe-dynamic-tag-management-training",
  "aws-training-dallas",
  "tableau-training-dallas",
  "rhce-training",
  "linux-security-fundamentals-training",
  "devops-training-dallas",
  "linux-networking-training",
  "linux-cluster-training",
  "ibm-curam-training",
  "ibm-emptoris-training",
  "juniper-contrail-training",
  "ibm-bigfix-platform-foundations-training",
  "check-point-security-administration-training",
  "nutanix-enterprise-cloud-platform-administration-training",
  "certified-network-defender-training",
  "altiris-training",
  "bmc-remedy-training",
  "aws-business-essentials-training",
  "go-training",
  "oracle-paas-training",
  "visual-studio-team-services-training",
  "nunit-training",
  "katalon-training",
  "selenium-with-ruby-training",
  "selenium-with-python-training",
  "selenium-with-java-training",
  "selenium-with-c-sharp-training",
  "selenium-with-jenkins-training",
  "jboss-soa-esb-training",
  "jboss-application-server-training",
  "jaspersoft-training",
  "microservices-architecture-training",
  "soapui-training",
  "demandware-training",
  "technical-writing-training",
  "worksoft-certify-training",
  "facets-training",
  "rsa-netwitness-training",
  "design-thinking-training",
  "knockoutjs-training",
  "informatica-cloud-training",
  "hyperion-enterprise-performance-management-training",
  "machine-learning-with-python-training",
  "sharepoint-admin-training",
  "deep-learning-with-python-training",
  "data-science-with-python-training",
  "clm-training",
  "microservices-training",
  "anaplan-training",
  "okta-training",
  "denodo-training",
  "intelligent-data-integration-training",
  "microsoft-azure-fabric-training",
  "cissp-certification-training",
  "data-science-with-r-training",
  "lightbend-akka-for-scala-training",
  "akka-training",
  "akka-framework-training",
  "ironpython-training",
  "cacti-training",
  "stata-training",
  "domo-training",
  "sisense-training",
  "rapidminer-training",
  "hp-alm-training",
  "cisco-data-virtualization-training",
  "tableau-prep-training",
  "salesforce-business-analyst-training",
  "peoplesoft-integration-broker-training",
  "ibm-db2-training",
  "informatica-metadata-manager-training",
  "asm-training",
  "csm-training",
  "keras-training",
  "tosca-training",
  "salesforce-cpq-training",
  "full-stack-training",
  "winshuttle-training",
  "bdd-training",
  "microsoft-flow-training",
  "bmc-marimba-training",
  "spring-boot-training",
  "powershell-training",
  "fisheye-crucible-training",
  "jama-training",
  "spring-cloud-training",
  "microservices-with-spring-cloud-training",
  "tasktop-training",
  "winautomation-training",
  "brightspot-training",
  "enovia-training",
  "postgresql-training",
  "hpe-simplivity-training",
  "pouchdb-training",
  "kotlin-training",
  "hpe-synergy-training",
  "angular-js-training",
  "netsuite-technical-training",
  "gocd-training",
  "windows-server-administration-training",
  "uft-training",
  "eggplant-training",
  "clojure-training",
  "prometheus-training",
  "oracle-enterprise-manager-cloud-control-training",
  "salesforce-field-service-lightning-training",
  "ptc-windchill-admin-training",
  "python-training-bangalore",
  "blockchain-training-bangalore",
  "ethical-hacking-course-in-bangalore",
  "tableau-training-bangalore",
  "api-testing-using-katalon-training",
  "oracle-cpq-training",
  "powerapps-training",
  "microsoft-azure-training-bangalore",
  "aws-certification-training-course-chennai",
  "salesforce-training-bangalore",
  "data-science-course-hyderabad",
  "data-science-course-bangalore",
  "power-bi-training-houston",
  "salesforce-training-hyderabad",
  "power-bi-training-toronto",
  "power-bi-training-hyderabad ",
  "pega-training-hyderabad",
  "pega-training-chennai",
  "python-training-chennai",
  "power-bi-training-bangalore",
  "microsoft-azure-training-virginia",
  "microsoft-azure-training-washington",
  "microsoft-azure-training-pennsylvania",
  "microsoft-azure-training-maryland",
  "microsoft-azure-training-hyderabad",
  "cyber-security-training-chennai",
  "cyber-security-training-hyderabad",
  "microsoft-azure-training-delhi",
  "aws-certification-training-pune",
  "microsoft-azure-training-pune",
  "microsoft-azure-training-chennai",
  "blockchain-training-hyderabad",
  "kubernetes-certification-training-new-york",
  "tableau-training-hyderabad",
  "kubernetes-training-bangalore",
  "kubernetes-training-hyderabad",
  "kubernetes-training-california",
  "aws-certification-training-bangalore",
  "artificial-intelligence-course-hyderabad",
  "power-bi-training-london",
  "ethical-hacking-training-hyderabad",
  "msbi-training-bangalore",
  "ansible-training-bangalore",
  "artificial-intelligence-course-bangalore",
  "aws-certification-training-delhi",
  "jboss-training-hyderabad",
  "aws-certification-training-ahmedabad",
  "tableau-training-mumbai",
  "iot-training-bangalore",
  "iot-training-pune",
  "ccna-training-noida",
  "splunk-training-new-york",
  "servicenow-training-bangalore",
  "power-bi-training-chicago",
  "power-bi-training-singapore",
  "tableau-training-chennai",
  "workday-financials-training",
  "tableau-training-pune",
  "power-bi-training-sydney",
  "ccna-training-bangalore",
  "apache-spark-training-bangalore",
  "artificial-intelligence-course-pune",
  "hyperion-training-hyderabad",
  "artificial-intelligence-course-dallas",
  "tableau-training-noida",
  "artificial-intelligence-course-new-york",
  "sccm-training-bangalore",
  "qlikview-training-bangalore",
  "aws-training-hyderabad",
  "powershell-training-bangalore",
  "linux-training-hyderabad",
  "ccna-training-gurgaon",
  "aws-training-kolkata",
  "devops-training-bangalore",
  "linux-training-bangalore",
  "jira-training-hyderabad",
  "tableau-training-chicago",
  "tableau-training-toronto",
  "tableau-training-singapore",
  "iot-training-hyderabad",
  "powershell-training-hyderabad",
  "jira-training-bangalore",
  "vmware-training-delhi",
  "labview-training-chennai",
  "qlikview-training-chennai",
  "devops-training-london",
  "aws-training-mumbai",
  "msbi-training-hyderabad",
  "rpa-training-hyderabad",
  "rpa-training-bangalore",
  "cyber-security-training-melbourne",
  "iot-training-chennai",
  "aws-training-london",
  "ethical-hacking-training-dallas",
  "linux-training-pune",
  "linux-training-chennai",
  "devops-training-pune",
  "iot-training-mumbai",
  "react-js-training-hyderabad",
  "react-js-training-bangalore",
  "salesforce-training-chicago",
  "vmware-training-chennai",
  "ccna-training-hyderabad",
  "salesforce-training-pune",
  "ethical-hacking-training-chennai",
  "servicenow-training-hyderabad",
  "aws-training-noida",
  "cyber-security-training-houston",
  "vmware-training-mumbai",
  "ccna-training-kolkata",
  "oracle-dba-training-bangalore",
  "ccna-training-pune",
  "aws-training-toronto",
  "vmware-training-pune",
  "hyperion-essbase-training",
  "servicenow-developer-training",
  "power-bi-training-chennai",
  "ccna-training-dallas",
  "vmware-training-hyderabad",
  "vmware-training-new-york",
  "oci-training",
  "power-automate-training",
  "google-cloud-training",
  "snowflake-training",
  "open-api-training",
  "certified-kubernetes-application-developer-training",
  "microsoft-azure-developer-associate-certification-training",
  "lean-training",
  "six-sigma-green-belt-training",
  "togaf-training",
  "azure-logic-apps-training",
];

export const course_headings = {
'116': 'Data Science Training',
'283': 'Linux Training and Certification Course',
'379': 'SQL Server DBA Training and Certification Course',
'440': 'Salesforce Training - Online Certification Course',
'201': 'Power BI Training Online',
'110': 'AWS Training and Certification Course',
'759': 'AWS Training in Chennai',
'398': 'QlikView Training & Certification Course',
'763': 'Power BI Training Houston',
'761': 'Data Science Course in Hyderabad',
'757': 'Microsoft Azure Training in Bangalore',
'762': 'Data Science Training Course in Bangalore',
'764': 'Salesforce Training in Hyderabad',
'632': 'DevOps Training in Dallas',
'607': 'Salesforce Training In Dallas',
'477': 'React JS Certification Training',
'617': 'Cyber Security Training in Dallas',
'760': 'Salesforce Training In Bangalore',
'767': 'Pega Certification Training in Hyderabad',
'569': 'Salesforce Training in Chennai',
'488': 'RPA UiPath Training and Certification',
'768': 'Pega Certification Training in Chennai',
'571': 'DevOps Training In Chennai',
'765': 'Power BI Training in Toronto',
'766': 'Power BI Training in Hyderabad',
'769': 'Python Training and Certification Course in Chennai',
'564': 'Informatica Training In Chennai',
'459': 'SQL Server Training and Certification Course',
'383': 'MongoDB Training and Certification Course',
'750': 'Blockchain Training in Bangalore ',
'446': 'UI Developer Training and Certification Course Online',
'712': 'Full Stack Training',
'559': 'VMware Training In Bangalore',
'486': 'Automation Anywhere Training and Certification Course',
'770': 'Power BI Training in Bangalore',
'620': 'Microsoft Azure Certification Training in Dallas',
'562': 'Cyber Security Training In Bangalore',
'771': 'Microsoft Azure Training in Virginia',
'772': 'Azure Certification Training in Washington',
'611': 'Informatica Training In Bangalore',
'773': 'Microsoft Azure Training in Pennsylvania',
'774': 'Microsoft Azure Training in Maryland',
'776': 'Microsoft Azure Training in Hyderabad',
'572': 'Microsoft Azure Training in New York - Certification Course',
'777': 'Cyber Security Training In Chennai',
'778': 'Cyber Security Training In Hyderabad',
'779': 'Microsoft Azure Training in Delhi - Certification Course',
'781': 'Azure Certification Training Course in Pune',
'782': 'Microsoft Azure Training in Chennai - Online Certification Course',
'783': 'Blockchain Training in Hyderabad',
'780': 'AWS Training in Pune',
'628': 'AWS Training in Dallas',
'784': 'Kubernetes Training and Certification Course in New York',
'786': 'Kubernetes Training in Bangalore and Certification Course',
'787': 'Kubernetes Training and Certification Course in Hyderabad',
'788': 'Kubernetes Training and Certification Course in California',
'785': 'Tableau Training in Hyderabad',
'392': 'Mulesoft Training - Mule 4 Online Course',
'533': 'Artificial Intelligence Training and Certification Course',
'790': 'Artificial Intelligence Course in Hyderabad - Online Certification',
'792': 'Ethical Hacking Training in Hyderabad',
'793': 'MSBI Training In Bangalore',
'752': 'Tableau Training in Bangalore',
'789': 'AWS Training in Bangalore',
'794': 'Ansible Training In Bangalore',
'789': 'AWS Training in Bangalore',
'791': 'Power BI Training in London',
'567': 'Python Training in New York',
'795': 'Artificial Intelligence Course in Bangalore - Online Certification',
'796': 'AWS Training in Delhi',
'612': 'Cognos Training in Dallas',
'797': 'JBoss Training in Hyderabad',
'574': 'QlikView Training In New York',
'618': 'QlikView Training in Dallas',
'798': 'AWS Training in Ahmedabad',
'614': 'Python Training and Certification Course in Dallas',
'748': 'Python Training in Bangalore',
'561': 'Tableau Training in New York',
'800': 'IoT Training In Bangalore',
'799': 'Tableau Training In Mumbai',
'801': 'IoT Training In Pune',
'802': 'CCNA Training in Noida',
'803': 'Splunk Training in New York',
'804': 'ServiceNow Training In Bangalore',
'805': 'Power BI Training in Chicago',
'806': 'Power BI Training in Singapore',
'807': 'Tableau Training in Chennai',
'809': 'Tableau Training in Pune',
'810': 'Power BI Training in Sydney',
'811': 'CCNA Training in Bangalore',
'812': 'Apache Spark Training In Bangalore',
'813': 'Artificial Intelligence Course in Pune - Online Certification',
'814': 'Hyperion Training in Hyderabad',
'815': 'Artificial Intelligence Training Course in Dallas: USA',
'609': 'Splunk Training in Dallas',
'816': 'Tableau Training in Noida',
'817': 'Artificial Intelligence Course in  New York: USA',
'629': 'Tableau Training in Dallas',
'560': 'AWS Training in New York',
'818': 'SCCM Training in Bangalore',
'819': 'QlikView Training in Bangalore',
'820': 'AWS Training in Hyderabad',
'821': 'PowerShell Training In Bangalore',
'822': 'Linux Training in Hyderabad - Online Course',
'823': 'CCNA Training in Gurgaon',
'824': 'AWS Training in Kolkata',
'825': 'DevOps Training In Bangalore',
'826': 'Linux Training in Bangalore - Online Course',
'827': 'Jira Training in Hyderabad',
'828': 'Tableau Training in Chicago',
'829': 'Tableau Training in Toronto',
'830': 'Tableau Training in Singapore',
'369': 'Microsoft Azure Training and Certification Course',
'143': 'IoT Training',
'831': 'IoT Training In Hyderabad',
'832': 'PowerShell Training In Hyderabad',
'833': 'Jira Training in Bangalore',
'834': 'VMware Training In Delhi',
'837': 'DevOps Training in London',
'838': 'AWS Training in Mumbai',
'835': 'LabVIEW Training in Chennai',
'839': 'MSBI Training In Hyderabad',
'836': 'QlikView Training in Chennai',
'481': 'RPA Training and Online Certification Course',
'840': 'RPA Training in Hyderabad',
'841': 'RPA Training in Bangalore',
'751': 'Ethical Hacking Training in Bangalore',
'842': 'Cyber Security Training in Melbourne',
'372': 'Oracle DBA Training and Certification Course',
'202': 'Oracle RAC Training and Certification Course',
'24': 'Oracle GoldenGate Training and Certification course',
'29': 'Oracle Exadata Training & Certification Course',
'843': 'IoT Training in Chennai',
'844': 'AWS Training in London',
'10': 'ServiceNow Training',
'845': 'Ethical Hacking Training in Dallas',
'540': 'Certified Kubernetes Administrator Training',
'846': 'Linux Training in Pune - Certification Course',
'847': 'Linux Training in Chennai - Certification Course',
'848': 'DevOps Training in Pune',
'849': 'IoT Training in Mumbai',
'850': 'React JS Training in Hyderabad',
'851': 'React JS Training in Bangalore',
'852': 'Salesforce Training In Chicago',
'853': 'VMware Training In Chennai',
'854': 'CCNA Training in Hyderabad',
'855': 'Salesforce Training in Pune',
'856': 'Ethical Hacking Training in Chennai',
'857': 'ServiceNow Training In Hyderabad',
'858': 'AWS Training in Noida',
'859': 'Cyber Security Training in Houston',
'860': 'VMware Training In Mumbai',
'861': 'CCNA Training in Kolkata',
'862': 'Oracle DBA Training in Bangalore',
'863': 'CCNA Training in Pune',
'864': 'AWS Training in Toronto',
'573': 'Hadoop Training in New York',
'371': 'ODI Training - Oracle Data Integrator Online Course',
'865': 'VMware Training In Pune',
'17': 'Oracle Fusion Financials Training and Certification',
'868': 'Power BI Training in Chennai',
'479': 'Looker Training',
'869': 'CCNA Training in Dallas',
'870': 'VMware Training In Hyderabad',
'871': 'VMware Training In New York',
'39': 'Scrum  Certification Training',
'673': 'Design Thinking Certification Training Course',
'158': 'Docker Certified Associate - DCA Online Training Course',
'877': 'Open API Training and Certification Course',
'878': 'CKAD Online Training - Certified Kubernetes Application Developer',
'56': 'CommVault Training and Certification Course',
'31': 'Selenium Training',
'461': 'Tableau Server Training (Tableau Administration)',

}